# Helper scripts to format the tables and data in the way we need

In [4]:
import pandas as pd

fullTable = pd.read_csv("/Users/gnickles/Desktop/FungalICS_Website/Data/LichenPaper/crmA/UneditedTable_crmA.tsv", sep="\t")
fullTable

,TreeTip_Name,Protein,Accession,Lichen,ICS_Clade,Species,Genus,Fungal_Class
0,Xylariaceae_sp_FL1272_KAI0164569.1,KAI0164569.1,GCA_022432385.1,NotLichen,crm_fused,Xylariaceae_sp_FL1272,NaN,Sordariomycetes
1,Xylariaceae_sp_FL1019_KAI1266947.1,KAI1266947.1,GCA_022578705.1,NotLichen,crm_fused,Xylariaceae_sp_FL1019,NaN,Sordariomycetes
2,Xylariaceae_sp_FL0594_KAI0398592.1,KAI0398592.1,GCA_022385605.1,NotLichen,crm_fused,Xylariaceae_sp_FL0594,NaN,Sordariomycetes
3,Xylaria_sp_FL1777_KAI1418874.1,KAI1418874.1,GCA_022578965.1,NotLichen,crm_fused,Xylaria_sp_FL1777,Xylaria,Sordariomycetes
4,Xylaria_palmicola_KAI0399761.1,KAI0399761.1,GCA_022385595.1,NotLichen,crm_fused,Xylaria_palmicola,Xylaria,Sordariomycetes
...,...,...,...,...,...,...,...,...
1326,Xylographa_pallens_MCJ1436518.1,MCJ1436518.1,GCA_022813845.1,Lichen,lichengroup2,Xylographa_pallens,Xylographa,Lecanoromycetes
1327,Xylographa_opegraphella_MCJ1283298.1,MCJ1283298.1,GCA_022813865.1,Lichen,lichengroup2,Xylographa_opegraphella,Xylographa,Lecanoromycetes
1328,Xylographa_carneopallida_MCJ1291148.1,MCJ1291148.1,GCA_022813885.1,Lichen,lichengroup2,Xylographa_carneopallida,Xylographa,Lecanoromycetes
1329,Xylographa_bjoerkii_MCJ1390691.1,MCJ1390691.1,GCA_022813905.1,Lichen,lichengroup2,Xylographa_bjoerkii,Xylographa,Lecanoromycetes
1330,Lambiella_insularis_MCJ1472382.1,MCJ1472382.1,GCA_022814265.1,Lichen,lichengroup2,Lambiella_insularis,Lambiella,Lecanoromycetes

In [ ]:
fullTable["ICS_Clade"] = fullTable["ICS_Clade"].astype(str)
crmOnly = fullTable[fullTable["ICS_Clade"].str.contains("crm")]
# dropping a couple of columns
dropThese = ["TreeTip_Name"]
crmOnly = crmOnly.drop(columns=dropThese)
#move the Lichen column to the end
lichenCol = crmOnly.pop("Lichen")
crmOnly["Lichen"] = lichenCol

crmOnly.to_csv("/Users/gnickles/Desktop/FungalICS_Website/Data/LichenPaper/crmA/EditedTable_crmA.tsv", sep="\t", index=False)

,Protein,Accession,ICS_Clade,Species,Genus,Fungal_Class,Lichen
0,KAI0164569.1,GCA_022432385.1,crm_fused,Xylariaceae_sp_FL1272,NaN,Sordariomycetes,NotLichen
1,KAI1266947.1,GCA_022578705.1,crm_fused,Xylariaceae_sp_FL1019,NaN,Sordariomycetes,NotLichen
2,KAI0398592.1,GCA_022385605.1,crm_fused,Xylariaceae_sp_FL0594,NaN,Sordariomycetes,NotLichen
3,KAI1418874.1,GCA_022578965.1,crm_fused,Xylaria_sp_FL1777,Xylaria,Sordariomycetes,NotLichen
4,KAI0399761.1,GCA_022385595.1,crm_fused,Xylaria_palmicola,Xylaria,Sordariomycetes,NotLichen
...,...,...,...,...,...,...,...
397,XP_033424409.1,GCF_003426965.1,crm_split,Aspergillus_tanneri,Aspergillus,Eurotiomycetes,NotLichen
398,XP_033402121.1,GCF_010093885.1,crm_split,Aplosporella_prunicola,Aplosporella,Dothideomycetes,NotLichen
399,KAF1919508.1,GCA_010094095.1,crm_split,Ampelomyces_quisqualis,Ampelomyces,Dothideomycetes,NotLichen
400,MCJ1314532.1,GCA_022814335.1,crm_split,Agyrium_rufum,Agyrium,Lecanoromycetes,Lichen
401,MCJ1312423.1,GCA_022814335.1,crm_split,Agyrium_rufum,Agyrium,Lecanoromycetes,Lichen